name: Build and Release NVDA Add-on

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install SCons
      run: pip install scons

    - name: Clean up dist folder
      run: rm -f dist/*.nvda-addon

    - name: Build .nvda-addon
      run: scons

    - name: Extract release notes
      id: changelog
      run: |
        VER="${{ github.ref_name }}"
        awk "/^## ${VER}/{flag=1;next}/^## /{flag=0}flag" release-notes.md > extracted-notes.txt

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          dist/*.nvda-addon
        body_path: extracted-notes.txt
